### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jasonh1995** [Mumblecraft/Mumblecraft-3#76]
The following bugs being experienced from users in the server are as follow:

First: Creating treated sticks using an Axe consumes the entire axe for perhaps 1 stick at most or does not work at all.

Second: Cannot create Brass gears to advance

**Comment by Cmptr7** [comment]
Treated sticks fixed and will be part of 1.2. Looking into brass gears

**Comment by Cmptr7** [comment]
Both are fixed in 1.2
